[pytest]
testpaths =
    dqn/tests
    hpo/tests
    distillation/tests
    nn_viz/tests
    q_learning/test
pythonpath =
    dqn/src
    dqn/tests
    hpo/src
    hpo/tests
    distillation/src
    distillation/tests
    nn_viz/src
    nn_viz/tests
    q_learning/src
addopts = -p no:cacheprovider
norecursedirs = .venv .pytest_cache pytest-cache-files-* notebooks src
filterwarnings =
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
