[pytest]
testpaths =
    dqn/tests
    hpo/tests
    q_learning/test
pythonpath =
    dqn/src
    dqn/tests
    hpo/src
    hpo/tests
    q_learning/src
addopts = -p no:cacheprovider
norecursedirs = .venv .pytest_cache pytest-cache-files-* notebooks src
