@startuml

hide footbox

participant ":StudyRunner" as runner
participant "study.py" as study_module
participant "study:Study" as study
participant "objective.py" as objective
participant ":SuggestParameterValues" as suggest_parameter_values
participant ":EnvironmentFactory" as environment_factory
participant ":VectorTrainer" as trainer
participant ":Trial" as trial

url of runner is [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/study.py:52:1]]
url of study_module is [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/study.py:1:1]]
url of study is [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/study.py:279:1]]
url of objective is [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/objective.py:134:1]]
url of suggest_parameter_values is [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/objective.py:19:1]]
url of environment_factory is [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/objective.py:23:1]]
url of trainer is [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/dqn/src/dqn/vector_training.py:115:1]]
url of trial is [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/objective.py:142:1]]

[-> runner : [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/study.py:71:1 run(study_name, suggest_parameter_values, n_trials)]]
activate runner

runner -> study_module : [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/study.py:127:1 run_study(...)]]
activate study_module

study_module -> study : [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/study.py:173:1 optimize(objective, n_trials=1)]]
activate study

study -> objective : [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/objective.py:142:1 objective(trial)]]
activate objective

objective -> suggest_parameter_values : [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/objective.py:143:1 suggest_parameter_values(trial, incumbent_params)]]
activate suggest_parameter_values
suggest_parameter_values -> trial : suggest_*(...)
activate trial
trial --> suggest_parameter_values : parameter value
deactivate trial
suggest_parameter_values --> objective : trial.params ergaenzt
deactivate suggest_parameter_values

objective -> objective : [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/objective.py:205:1 vector_training_config(params)]]

objective -> environment_factory : [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/objective.py:23:1 make_training_env(num_envs)]]
activate environment_factory
deactivate environment_factory

objective -> trainer : [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/dqn/src/dqn/vector_training.py:166:1 train(training_config)]]
activate trainer
trainer --> objective : training result
deactivate trainer

objective -> environment_factory : [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/objective.py:26:1 evaluation_envs()]]
activate environment_factory
deactivate environment_factory

objective -> objective : [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/objective.py:221:1 evaluate_greedy_q_net(...)]]

objective --> study : mean world score
deactivate objective
deactivate study

study_module --> runner : study
deactivate study_module

runner -> study_module : [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/study.py:182:1 select_robust_best(...)]]
activate study_module
study_module --> runner : selected parameters
deactivate study_module

runner -> runner : [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/study.py:114:1 incumbent_score aktualisieren]]
runner -> runner : [[vscode://file/C:/Users/mwehle/Documents/_P/KI/rl_lab/hpo/src/hpo/study.py:123:1 study in studies ablegen]]
deactivate runner

@enduml
