@startuml

!include ../puml_links.iuml

hide footbox

participant "trainer:VectorTrainer" as trainer
participant "env:VectorEnv" as env
participant "memory:VectorReplayMemory" as memory
participant "q_net:DQN" as q_net
participant "target_net:DQN" as target_net
participant "optimizer:AdamW" as optimizer

url of trainer is [[WORKSPACE_ROOT/dqn/src/dqn/vector_training.py:115:1]]
url of memory is [[WORKSPACE_ROOT/dqn/src/dqn/vector_training.py:51:1]]
url of q_net is [[WORKSPACE_ROOT/dqn/src/dqn/model.py:8:1]]
url of target_net is [[WORKSPACE_ROOT/dqn/src/dqn/model.py:8:1]]
url of env is [[https://gymnasium.farama.org/api/vector/]]
url of optimizer is [[https://docs.pytorch.org/docs/stable/generated/torch.optim.AdamW.html]]

[-> trainer : [[WORKSPACE_ROOT/dqn/src/dqn/vector_training.py:166:1 train(config)]]
activate trainer

trainer -> env : [[https://gymnasium.farama.org/api/vector/ reset()]]
activate env
env --> trainer : observations
deactivate env

trainer -> env : [[https://gymnasium.farama.org/api/vector/ step(actions)]]
activate env
env --> trainer : observations, rewards, done
deactivate env

trainer -> memory : [[WORKSPACE_ROOT/dqn/src/dqn/vector_training.py:70:1 push_batch(...)]]
activate memory
deactivate memory

trainer -> memory : [[WORKSPACE_ROOT/dqn/src/dqn/vector_training.py:100:1 sample(batch_size, device)]]
activate memory
memory --> trainer : replay batch
deactivate memory

trainer -> q_net : [[WORKSPACE_ROOT/dqn/src/dqn/model.py:15:1 q_net(states)]]
activate q_net
q_net --> trainer : Q-values
deactivate q_net

trainer -> target_net : [[WORKSPACE_ROOT/dqn/src/dqn/model.py:15:1 target_net(next_states)]]
activate target_net
target_net --> trainer : target Q-values
deactivate target_net

trainer -> optimizer : [[https://docs.pytorch.org/docs/stable/generated/torch.optim.AdamW.html step()]]
activate optimizer
deactivate optimizer

trainer -->[ : VectorTrainingResult
deactivate trainer

@enduml
