"""Extract Eagle body drawing ops by subtracting the static leg ops.

This is a design helper. It produces the counterpart to
``detailed/eagle_legs_pygame.py`` so later renderers can attach the Eagle body
to Gymnasium's lander body and the legs to Gymnasium's physical leg bodies.
"""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from pathlib import Path
import sys
from typing import TypeAlias

Point: TypeAlias = tuple[float, float]
Op: TypeAlias = tuple[str, str | None, str | None, float, list[Point]]

GRAPHICS_DIR = Path(__file__).resolve().parents[1]
DETAILED_DIR = GRAPHICS_DIR / "detailed"
DEFAULT_OUTPUT = DETAILED_DIR / "eagle_body_pygame.py"


def extract_body_ops(ops: Iterable[Op], leg_ops: Iterable[Op]) -> list[Op]:
    """Return all Eagle ops except the already extracted landing-leg ops."""

    leg_keys = {_op_key(op) for op in leg_ops}
    return [
        (kind, fill, stroke, stroke_width, list(points))
        for kind, fill, stroke, stroke_width, points in ops
        if _op_key((kind, fill, stroke, stroke_width, points)) not in leg_keys
    ]


def write_pygame_module(path: str | Path, ops: Sequence[Op]) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    text = f'''"""Extracted static Eagle body Pygame drawing ops.

Generated by ops/extract_eagle_body.py from eagle_lander_pygame.py
minus eagle_legs_pygame.py.
This is a design reference, not runtime code.
"""

import pygame

SVG_WIDTH = 490
SVG_HEIGHT = 367

EAGLE_BODY_OPS = {ops!r}


def _rgb(hex_color):
    if hex_color is None or hex_color == "none":
        return None
    hex_color = hex_color.lstrip("#")
    return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))


def _transform_points(points, x, y, scale):
    return [(int(round(x + px * scale)), int(round(y + py * scale))) for px, py in points]


def draw_eagle_body(surface, x=0, y=0, scale=1.0, scale_strokes=True):
    for kind, fill_hex, stroke_hex, stroke_width, points in EAGLE_BODY_OPS:
        pts = _transform_points(points, x, y, scale)
        fill = _rgb(fill_hex)
        stroke = _rgb(stroke_hex)
        width = max(1, int(round(stroke_width * scale))) if scale_strokes else max(1, int(round(stroke_width)))

        if kind == "polygon":
            if fill is not None:
                pygame.draw.polygon(surface, fill, pts, 0)
            if stroke is not None and len(pts) >= 2:
                pygame.draw.polygon(surface, stroke, pts, width)
        elif kind == "polyline":
            color = stroke or fill
            if color is not None and len(pts) >= 2:
                pygame.draw.lines(surface, color, False, pts, width)


def make_eagle_body_surface(scale=1.0, background=None):
    w = int(round(SVG_WIDTH * scale))
    h = int(round(SVG_HEIGHT * scale))
    surface = pygame.Surface((w, h), pygame.SRCALPHA)
    if background is not None:
        surface.fill(background)
    draw_eagle_body(surface, 0, 0, scale)
    return surface


def save_eagle_body_png(filename="eagle_body.png", scale=1.0, background=(255, 255, 255)):
    pygame.init()
    surface = make_eagle_body_surface(scale=scale, background=background)
    pygame.image.save(surface, filename)
    return filename
'''
    path.write_text(text, encoding="utf-8")


def _op_key(op: Op):
    kind, fill, stroke, stroke_width, points = op
    return kind, fill, stroke, stroke_width, tuple(points)


def _load_eagle_ops() -> list[Op]:
    sys.path.insert(0, str(DETAILED_DIR))
    from eagle_lander_pygame import EAGLE_OPS

    return [(kind, fill, stroke, stroke_width, list(points)) for kind, fill, stroke, stroke_width, points in EAGLE_OPS]


def _load_leg_ops() -> list[Op]:
    sys.path.insert(0, str(DETAILED_DIR))
    from eagle_legs_pygame import EAGLE_LEG_OPS

    return [(kind, fill, stroke, stroke_width, list(points)) for kind, fill, stroke, stroke_width, points in EAGLE_LEG_OPS]


def main() -> int:
    ops = extract_body_ops(_load_eagle_ops(), _load_leg_ops())
    write_pygame_module(DEFAULT_OUTPUT, ops)
    print(f"body ops: {len(ops)}")
    print(f"wrote: {DEFAULT_OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
