"""Extract landing-leg drawing ops from the detailed Eagle Pygame module.

This is a design helper. It keeps the static Eagle leg graphics as a reference
for building later Gymnasium-driven moving legs.
"""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from pathlib import Path
import sys
from typing import TypeAlias

Point: TypeAlias = tuple[float, float]
Op: TypeAlias = tuple[str, str | None, str | None, float, list[Point]]

GRAPHICS_DIR = Path(__file__).resolve().parents[1]
DETAILED_DIR = GRAPHICS_DIR / "detailed"
DEFAULT_OUTPUT = DETAILED_DIR / "eagle_legs_pygame.py"


def extract_leg_ops(ops: Iterable[Op]) -> list[Op]:
    """Return the outer left and right landing-leg ops from the Eagle drawing."""

    return [
        (kind, fill, stroke, stroke_width, list(points))
        for kind, fill, stroke, stroke_width, points in ops
        if _is_outer_leg(points)
    ]


def write_pygame_module(path: str | Path, ops: Sequence[Op]) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    text = f'''"""Extracted static Eagle landing-leg Pygame drawing ops.

Generated by ops/extract_eagle_legs.py from eagle_lander_pygame.py.
This is a design reference, not runtime code.
"""

import pygame

SVG_WIDTH = 490
SVG_HEIGHT = 367

EAGLE_LEG_OPS = {ops!r}


def _rgb(hex_color):
    if hex_color is None or hex_color == "none":
        return None
    hex_color = hex_color.lstrip("#")
    return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))


def _transform_points(points, x, y, scale):
    return [(int(round(x + px * scale)), int(round(y + py * scale))) for px, py in points]


def draw_eagle_legs(surface, x=0, y=0, scale=1.0, scale_strokes=True):
    for kind, fill_hex, stroke_hex, stroke_width, points in EAGLE_LEG_OPS:
        pts = _transform_points(points, x, y, scale)
        fill = _rgb(fill_hex)
        stroke = _rgb(stroke_hex)
        width = max(1, int(round(stroke_width * scale))) if scale_strokes else max(1, int(round(stroke_width)))

        if kind == "polygon":
            if fill is not None:
                pygame.draw.polygon(surface, fill, pts, 0)
            if stroke is not None and len(pts) >= 2:
                pygame.draw.polygon(surface, stroke, pts, width)
        elif kind == "polyline":
            color = stroke or fill
            if color is not None and len(pts) >= 2:
                pygame.draw.lines(surface, color, False, pts, width)


def make_eagle_legs_surface(scale=1.0, background=None):
    w = int(round(SVG_WIDTH * scale))
    h = int(round(SVG_HEIGHT * scale))
    surface = pygame.Surface((w, h), pygame.SRCALPHA)
    if background is not None:
        surface.fill(background)
    draw_eagle_legs(surface, 0, 0, scale)
    return surface


def save_eagle_legs_png(filename="eagle_legs.png", scale=1.0, background=(255, 255, 255)):
    pygame.init()
    surface = make_eagle_legs_surface(scale=scale, background=background)
    pygame.image.save(surface, filename)
    return filename
'''
    path.write_text(text, encoding="utf-8")


def _is_outer_leg(points: Sequence[Point]) -> bool:
    x1, y1, x2, y2 = _bbox(points)
    width = x2 - x1
    height = y2 - y1

    is_left = x2 <= 150
    is_right = x1 >= 340
    is_lower = y2 >= 220
    is_leg_like = height >= 6 or width >= 10
    return (is_left or is_right) and is_lower and is_leg_like


def _bbox(points: Sequence[Point]) -> tuple[float, float, float, float]:
    xs = [point[0] for point in points]
    ys = [point[1] for point in points]
    return min(xs), min(ys), max(xs), max(ys)


def _load_eagle_ops() -> list[Op]:
    sys.path.insert(0, str(DETAILED_DIR))
    from eagle_lander_pygame import EAGLE_OPS

    return [(kind, fill, stroke, stroke_width, list(points)) for kind, fill, stroke, stroke_width, points in EAGLE_OPS]


def main() -> int:
    ops = extract_leg_ops(_load_eagle_ops())
    write_pygame_module(DEFAULT_OUTPUT, ops)
    print(f"leg ops: {len(ops)}")
    print(f"wrote: {DEFAULT_OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
