"""Simplify the detailed Eagle Pygame drawing ops.

This is a design helper, not runtime code. It experiments with making the
detailed Eagle drawing from ``eagle_lander_pygame.py`` coarser by combining:

- Ramer-Douglas-Peucker point simplification
- optional removal of very small shapes
- optional coordinate snapping

Example from the repository root:

    python hpo/_experimental/lander_rendering/ops/simplify_eagle_ops.py --epsilon 2 --snap 0.5
"""

from __future__ import annotations

import argparse
from collections.abc import Iterable, Sequence
from pathlib import Path
import sys
from typing import TypeAlias

Point: TypeAlias = tuple[float, float]
Op: TypeAlias = tuple[str, str | None, str | None, float, list[Point]]

GRAPHICS_DIR = Path(__file__).resolve().parents[1]
DETAILED_DIR = GRAPHICS_DIR / "detailed"
DEFAULT_OUTPUT = DETAILED_DIR / "eagle_lander_pygame_simplified.py"


def simplify_ops(
    ops: Iterable[Op],
    *,
    epsilon: float,
    min_size: float = 0.0,
    min_area: float = 0.0,
    min_length: float = 0.0,
    snap: float | None = None,
) -> list[Op]:
    """Return simplified drawing ops.

    ``epsilon`` controls Douglas-Peucker simplification. Larger values remove
    more points. ``min_size``, ``min_area`` and ``min_length`` remove tiny
    separate shapes that Douglas-Peucker cannot remove by itself.
    """

    simplified: list[Op] = []
    for kind, fill, stroke, stroke_width, points in ops:
        if _drop_shape(kind, points, min_size=min_size, min_area=min_area, min_length=min_length):
            continue

        if kind == "polygon":
            new_points = simplify_polygon(points, epsilon)
            if len(new_points) < 3:
                continue
        elif kind == "polyline":
            new_points = simplify_polyline(points, epsilon)
            if len(new_points) < 2:
                continue
        else:
            new_points = list(points)

        if snap is not None and snap > 0:
            new_points = _dedupe_neighbors([_snap_point(point, snap) for point in new_points])

        if not _drop_shape(kind, new_points, min_size=min_size, min_area=min_area, min_length=min_length):
            simplified.append((kind, fill, stroke, stroke_width, new_points))

    return simplified


def simplify_polyline(points: Sequence[Point], epsilon: float) -> list[Point]:
    """Simplify an open polyline with Ramer-Douglas-Peucker."""

    if len(points) <= 2 or epsilon <= 0:
        return list(points)

    first = points[0]
    last = points[-1]
    max_distance = -1.0
    split_index = 0

    for index, point in enumerate(points[1:-1], start=1):
        distance = _point_line_distance(point, first, last)
        if distance > max_distance:
            max_distance = distance
            split_index = index

    if max_distance <= epsilon:
        return [first, last]

    left = simplify_polyline(points[: split_index + 1], epsilon)
    right = simplify_polyline(points[split_index:], epsilon)
    return left[:-1] + right


def simplify_polygon(points: Sequence[Point], epsilon: float) -> list[Point]:
    """Simplify a polygon contour while keeping it open in the returned data."""

    if len(points) <= 3 or epsilon <= 0:
        return list(points)

    closed = list(points)
    if closed[0] != closed[-1]:
        closed.append(closed[0])

    simplified = simplify_polyline(closed, epsilon)
    if simplified and simplified[0] == simplified[-1]:
        simplified.pop()
    return simplified


def write_pygame_module(path: str | Path, ops: Sequence[Op], *, source: str, epsilon: float) -> None:
    """Write a standalone Pygame module containing the simplified ops."""

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    text = f'''"""Simplified Eagle Pygame drawing ops.

Generated by ops/simplify_eagle_ops.py from {source}.
Douglas-Peucker epsilon: {epsilon}
"""

import pygame

SVG_WIDTH = 490
SVG_HEIGHT = 367

EAGLE_OPS = {ops!r}


def _rgb(hex_color):
    if hex_color is None or hex_color == "none":
        return None
    hex_color = hex_color.lstrip("#")
    return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))


def _transform_points(points, x, y, scale):
    return [(int(round(x + px * scale)), int(round(y + py * scale))) for px, py in points]


def draw_eagle(surface, x=0, y=0, scale=1.0, scale_strokes=True):
    for kind, fill_hex, stroke_hex, stroke_width, points in EAGLE_OPS:
        pts = _transform_points(points, x, y, scale)
        fill = _rgb(fill_hex)
        stroke = _rgb(stroke_hex)
        width = max(1, int(round(stroke_width * scale))) if scale_strokes else max(1, int(round(stroke_width)))

        if kind == "polygon":
            if fill is not None:
                pygame.draw.polygon(surface, fill, pts, 0)
            if stroke is not None and len(pts) >= 2:
                pygame.draw.polygon(surface, stroke, pts, width)
        elif kind == "polyline":
            color = stroke or fill
            if color is not None and len(pts) >= 2:
                pygame.draw.lines(surface, color, False, pts, width)


def make_eagle_surface(scale=1.0, background=None):
    w = int(round(SVG_WIDTH * scale))
    h = int(round(SVG_HEIGHT * scale))
    surface = pygame.Surface((w, h), pygame.SRCALPHA)
    if background is not None:
        surface.fill(background)
    draw_eagle(surface, 0, 0, scale)
    return surface


def save_eagle_png(filename="eagle_lander_simplified.png", scale=1.0, background=(255, 255, 255)):
    pygame.init()
    surface = make_eagle_surface(scale=scale, background=background)
    pygame.image.save(surface, filename)
    return filename
'''
    path.write_text(text, encoding="utf-8")


def _drop_shape(
    kind: str,
    points: Sequence[Point],
    *,
    min_size: float,
    min_area: float,
    min_length: float,
) -> bool:
    if not points:
        return True

    width, height = _bbox_size(points)
    if min_size > 0 and width < min_size and height < min_size:
        return True

    if kind == "polygon" and min_area > 0 and abs(_polygon_area(points)) < min_area:
        return True

    if kind == "polyline" and min_length > 0 and _polyline_length(points) < min_length:
        return True

    return False


def _point_line_distance(point: Point, start: Point, end: Point) -> float:
    px, py = point
    sx, sy = start
    ex, ey = end
    dx = ex - sx
    dy = ey - sy

    if dx == 0 and dy == 0:
        return ((px - sx) ** 2 + (py - sy) ** 2) ** 0.5

    numerator = abs(dy * px - dx * py + ex * sy - ey * sx)
    denominator = (dx * dx + dy * dy) ** 0.5
    return numerator / denominator


def _bbox_size(points: Sequence[Point]) -> tuple[float, float]:
    xs = [point[0] for point in points]
    ys = [point[1] for point in points]
    return max(xs) - min(xs), max(ys) - min(ys)


def _polygon_area(points: Sequence[Point]) -> float:
    if len(points) < 3:
        return 0.0
    area = 0.0
    previous = points[-1]
    for point in points:
        area += previous[0] * point[1] - point[0] * previous[1]
        previous = point
    return area / 2.0


def _polyline_length(points: Sequence[Point]) -> float:
    return sum(
        ((b[0] - a[0]) ** 2 + (b[1] - a[1]) ** 2) ** 0.5
        for a, b in zip(points, points[1:], strict=False)
    )


def _snap_point(point: Point, grid: float) -> Point:
    return round(point[0] / grid) * grid, round(point[1] / grid) * grid


def _dedupe_neighbors(points: Sequence[Point]) -> list[Point]:
    deduped: list[Point] = []
    for point in points:
        if not deduped or point != deduped[-1]:
            deduped.append(point)
    return deduped


def _load_eagle_ops() -> list[Op]:
    sys.path.insert(0, str(DETAILED_DIR))
    from eagle_lander_pygame import EAGLE_OPS

    return [(kind, fill, stroke, stroke_width, list(points)) for kind, fill, stroke, stroke_width, points in EAGLE_OPS]


def _point_count(ops: Iterable[Op]) -> int:
    return sum(len(points) for _, _, _, _, points in ops)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--epsilon", type=float, default=2.0, help="Douglas-Peucker tolerance in source pixels.")
    parser.add_argument("--min-size", type=float, default=0.0, help="Drop shapes whose bbox width and height are both smaller than this.")
    parser.add_argument("--min-area", type=float, default=0.0, help="Drop polygons below this absolute area.")
    parser.add_argument("--min-length", type=float, default=0.0, help="Drop polylines below this length.")
    parser.add_argument("--snap", type=float, default=0.0, help="Snap coordinates to this grid. 0 disables snapping.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Generated Pygame module path.")
    args = parser.parse_args(argv)

    original = _load_eagle_ops()
    simplified = simplify_ops(
        original,
        epsilon=args.epsilon,
        min_size=args.min_size,
        min_area=args.min_area,
        min_length=args.min_length,
        snap=(args.snap if args.snap > 0 else None),
    )
    write_pygame_module(args.output, simplified, source="eagle_lander_pygame.py", epsilon=args.epsilon)

    print(f"ops: {len(original)} -> {len(simplified)}")
    print(f"points: {_point_count(original)} -> {_point_count(simplified)}")
    print(f"wrote: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
